<a href="https://colab.research.google.com/github/WazedKhan/Pytorch/blob/main/00_Pytorch_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
torch.__version__

'1.13.1+cpu'

In [3]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


### Introduction to Tensor:

---



In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
type(scalar)

torch.Tensor

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
# vector 
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [2, 4, 8]
                        ]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 4, 8]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

In [17]:
# create a random tensor of size 
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.8687, 0.4457, 0.8142, 0.9545],
         [0.5269, 0.3892, 0.9674, 0.3733],
         [0.6410, 0.8038, 0.6477, 0.0898]]),
 torch.float32)

In [18]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(244, 244, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

In [19]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [20]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating a range and tensors like

In [21]:
torch.__version__

'1.13.1+cpu'

In [22]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# the same shape as another tensor
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
ten_ones = torch.ones_like(zero_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# _Precision is the amount of detail used to describe a number_

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

## Tensor Datatype

**Note:** Tensor data type is one of the 3 big error in Pytorch and Deep Learning that we will run into: 
1. Tensor not right type
2. Tensor not right shape
3. Tensor not on the right device

In [25]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what data type is the tensor (e.g float32 or float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensor operation

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [26]:
# converting data type 32 to 16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

### Getting information from tensors
1. Tensor not right data type - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensor not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensor not on the right device - to get device from a tensor, can use `tensor.device`

In [27]:
# create a random tensor
some_tensor = torch.rand(3, 4)
# find out detailed about it
print(some_tensor)
print(f"Shape of the tensor: {some_tensor.shape}")
print(f"Data Type of tensor: {some_tensor.dtype}")
print(f"The tensor is stored on: {some_tensor.device}")

tensor([[0.4705, 0.5349, 0.6651, 0.7979],
        [0.4712, 0.4125, 0.2680, 0.5577],
        [0.8367, 0.5822, 0.0264, 0.7146]])
Shape of the tensor: torch.Size([3, 4])
Data Type of tensor: torch.float32
The tensor is stored on: cpu


### Manipulating tensors (tensor operations)
Tensor Operation Includes:
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication


Basic operations

In [28]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [29]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [30]:
tensor * 10

tensor([10, 20, 30])

In [31]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

tensor won't change until or unless it has been reassign 

In [32]:
# tensor = tensor*10
tensor

tensor([1, 2, 3])

### Matrix multiplication
- Two main ways to performing multiplication in neural networks and deep learning
1. Element wise multiplication
2. Matrix multiplication (dot product)

In [33]:
# element-wise multiplication
print(tensor, "*", tensor )
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [34]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [35]:
%%time
1*1 + 2*2 + 3*3 

CPU times: total: 0 ns
Wall time: 0 ns


14

In [36]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [37]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: total: 15.6 ms
Wall time: 1e+03 µs


tensor(14)

In [38]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### One of the most common errors in deep learning (shape errors)
Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

1. The **Inner Dimension** must match

- `(3, 2) @ (3, 2)` this won't work
- `(2, 3) @ (3, 2)` will work
- `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **Outer Dimension**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`


In [ ]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

Note: We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.

In [40]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [41]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [42]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [43]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

The `torch.nn.Linear()` module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input x and a weights matrix A.


In [ ]:
linear = torch.nn.Linear(in_features=2, out_features=6)

### Finding the min, mean, max, sum etc (Tensor Aggregation)

In [44]:
# create a new tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
# find the min and max and mean
min = torch.min(x)
max = torch.max(x)
mean = torch.mean(x)
print(f"Min: {min}, Mean: {mean}, Max: {max}")

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long