<a href="https://colab.research.google.com/github/WazedKhan/Pytorch/blob/main/00_Pytorch_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
torch.__version__

'2.0.0+cpu'

In [4]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


### Introduction to Tensor:

---



In [5]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
type(scalar)

torch.Tensor

In [7]:
scalar.ndim

0

In [8]:
scalar.item()

7

In [9]:
# vector 
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [2, 4, 8]
                        ]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 4, 8]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

In [18]:
# create a random tensor of size 
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.0527, 0.6872, 0.1838, 0.8866],
         [0.2272, 0.4584, 0.6164, 0.3337],
         [0.0221, 0.6970, 0.7480, 0.8059]]),
 torch.float32)

In [19]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(244, 244, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

In [21]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [22]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating a range and tensors like

In [23]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# the same shape as another tensor
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
ten_ones = torch.ones_like(zero_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# _Precision is the amount of detail used to describe a number_

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

## Tensor Datatype

In [26]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [27]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) #torch.half would also work
float_16_tensor.dtype

torch.float16

### Getting information from tensors

In [28]:
# create a random tensor
some_tensor = torch.rand(3, 4)
# find out detailed about it
print(some_tensor)
print(f"Shape of the tensor: {some_tensor.shape}")
print(f"Data Type of tensor: {some_tensor.dtype}")
print(f"The tensor is stored on: {some_tensor.device}")

tensor([[0.8917, 0.6556, 0.6322, 0.6755],
        [0.4441, 0.9209, 0.2295, 0.1461],
        [0.7811, 0.1599, 0.1224, 0.1028]])
Shape of the tensor: torch.Size([3, 4])
Data Type of tensor: torch.float32
The tensor is stored on: cpu


### Manipulating tensors (tensor operations)


Basic operations

In [30]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [31]:
tensor * 10

tensor([10, 20, 30])

tensor won't change until or unless it has been reassign 

In [33]:
tensor = tensor*10
tensor

tensor([110, 120, 130])

In [34]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([110, 120, 130]) * tensor([110, 120, 130])
Equals: tensor([12100, 14400, 16900])
